AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Rakefile

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/ParameterLists:
  Max: 6
